name: Notifications to Microsoft Teams

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Notify on Push
        if: github.event_name == 'push'
        run: |
          curl -H "Content-Type: application/json" -d "{\"text\": \"🔔 New Push to Main: ${GITHUB_REF} by ${GITHUB_ACTOR}. Commit message: '${{ github.event.commits[0].message }}'.\"}" ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTOR: ${{ github.actor }}
      - name: Notify on Pull Request
        if: github.event_name == 'pull_request'
        run: |
          curl -H "Content-Type: application/json" -d "{\"text\": \"🔔 Pull Request : ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}. Action: ${{ github.event.action }}, URL: ${{ github.event.pull_request.html_url }}.\"}" ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
